### ISSUE TITLE
smartthings

### ISSUE THREAD

**Issue by alsdk3407** [SmartThingsCommunity/st-device-sdk-c-ref#103]
https://github.com/SmartThingsCommunity/st-device-sdk-c-ref/issues/101#issue-1009635059

**Comment by alsdk3407** [comment]
[https://github.com/SmartThingsCommunity/st-device-sdk-c-ref/issues/101#issue-1009635059](url)

**Comment by Kwang-Hui** [comment]
Hi, I can't find any contents from this issue.
So closing
