### ISSUE TITLE
[https://github.com/SmartThingsCommunity/st-device-sdk-c-ref/issues/101#issue-1009635059](url)

### ISSUE THREAD

**Issue by alsdk3407** [SmartThingsCommunity/st-device-sdk-c-ref#104]
[https://github.com/SmartThingsCommunity/st-device-sdk-c-ref/issues/101#issue-1009635059](url)https://github.com/SmartThingsCommunity/st-device-sdk-c-ref/issues/103#issuecomment-929106731_

**Comment by alsdk3407** [comment]
> [https://github.com/SmartThingsCommunity/st-device-sdk-c-ref/issues/101#issue-1009635059](url)[#103 (comment)](https://github.com/SmartThingsCommunity/st-device-sdk-c-ref/issues/103#issuecomment-929106731)_

**Comment by Kwang-Hui** [comment]
Hi, I can't find any contents from this issue.
So closing
