### ISSUE TITLE
> [https://github.com/SmartThingsCommunity/st-device-sdk-c-ref/issues/101#issue-1009635059](url)[#103 (comment)](https://github.com/SmartThingsCommunity/st-device-sdk-c-ref/issues/103#issuecomment-929106731)_

### ISSUE THREAD

**Issue by alsdk3407** [SmartThingsCommunity/st-device-sdk-c-ref#105]
> [https://github.com/SmartThingsCommunity/st-device-sdk-c-ref/issues/101#issue-1009635059](url)[#103 (comment)](https://github.com/SmartThingsCommunity/st-device-sdk-c-ref/issues/103#issuecomment-929106731)_

_Originally posted by @alsdk3407 in https://github.com/SmartThingsCommunity/st-device-sdk-c-ref/issues/104#issuecomment-929107877_

**Comment by Kwang-Hui** [comment]
Hi, I can't find any contents from this issue.
So closing
