### ISSUE TITLE
"WIFI_STA_CONNECT_BIT event Timeout" error when finishing Onboarding on ESP8266

### ISSUE THREAD

**Issue by tatyanavolkova** [SmartThingsCommunity/st-device-sdk-c-ref#110]
Hello everyone,

Not long ago a new error appeared, when trying to Direct-connect a ESP8266 board to SmartThings. I used a switch_example from this repo without any modifications. At first all goes well, the board is discovered and the phone asks which WiFi network to use. On the last step of Onboarding, the following error occurs:

E (134720) [IoT]: iot_bsp_wifi_set_mode(337) > WIFI_STA_CONNECT_BIT event Timeout
E (134726) [IoT]: _do_iot_main_command(564) > failed to set wifi_set_mode

After that, an error with code 86-002 appears on smartphone screen.

It is certainly a new error, as before (~several month ago) I repeated the same steps and all worked like charm. I used the same board, the same program and same developer account.

See full log in the attach
[wifi_error.log](https://github.com/SmartThingsCommunity/st-device-sdk-c-ref/files/7550375/wifi_error.log)

**Comment by jsp0929** [comment]
I got same thing with stdk v1.7.3. Hope this will be resolved soon!

**Comment by stdk-scm** [comment]
Dear all,
Thank you for using, concerning and reporting this.
We're investigating this.
I'll update soon.

**Comment by jy0209-kim** [comment]
Dear all,
This is resolved in v1.7.4.
There was an update to detect station disconnection during SoftAP mode and it made trouble in esp8266 due to the difference in performance between esp32.
Please try onboarding with v1.7.4 and let me know if you have trouble.
BR, Jiyoung.
