### ISSUE TITLE
About ESP8266 compilation issues

### ISSUE THREAD

**Issue by hangsome-xiang** [SmartThingsCommunity/st-device-sdk-c-ref#119]
I encountered a problem that I could not solve by myself. The specific output log is as follows:
Generating esp8266.project.ld
Traceback (most recent call last):
  File "/home/***/document/st-device-sdk-c-ref/bsp/esp8266/tools/ldgen/ldgen.py", line 150, in <module>
    main()
  File "/home/***/document/st-device-sdk-c-ref/bsp/esp8266/tools/ldgen/ldgen.py", line 106, in main
    dump = StringIO(subprocess.check_output([objdump, "-h", library]).decode())
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 21: ordinal not in range(128)
make: *** [/home/***/document/st-device-sdk-c-ref/bsp/esp8266/components/esp8266/Makefile.projbuild:74：/home/***/document/st-device-sdk-c-ref/apps/esp8266/switch_example/build/esp8266/esp8266.project.ld] error 1

**Comment by Kwang-Hui** [comment]
Hi, as you can see from the submodule configuration [here](https://github.com/SmartThingsCommunity/st-device-sdk-c-ref/blob/6ec0fe5dfc0131684168793a619939460ba7cc95/.gitmodules#L13). it is depends on ESP8266_RTOS_SDK from Espressif.
I think there is some environment problem while setting up ESP8266_RTOS_SDK. Coud you refer https://docs.espressif.com/projects/esp8266-rtos-sdk/en/latest/get-started/index.html ?
