### ISSUE TITLE
Build process very slow

### ISSUE THREAD

**Issue by ervinnotari** [SmartThingsCommunity/st-device-sdk-c-ref#124]
I'll like to ask if building process is same slow realy or I'm make some wrong. Because for me has taken 2 - 3 hours to complete.

I'm build switch_example in a ESP8266 using comand  `python3 build.py apps/esp8266/switch_example`. And I using to work a subsystem wsl2 linux. The build process is work normaly, after flash to device de system work corretly. But build is very too slowly.

**Comment by junyoun-kim** [comment]
Could you try it esp-sdk sample example? Does it also take that long?

**Comment by junyoun-kim** [comment]
Hello, @ervinnotari  Is there any more questions? We will close this issue if no more updates.
