### ISSUE TITLE
esp32 build error (switch example)

### ISSUE THREAD

**Issue by asurada92** [SmartThingsCommunity/st-device-sdk-c-ref#139]
hello,
i’m trying to get setup for SDK for esp32 board
After all setting( setup esd-if, etc…)
when i execute build.py (ST SDK),
`Toolchain path: /home/yhpark/esp/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc
WARNING: Toolchain version is not supported: crosstool-ng-1.22.0-97-gc752ad5
Expected to see version: crosstool-ng-1.22.0-96-g2852398
Please check ESP-IDF setup instructions and update the toolchain, or proceed at your own risk.
Compiler version: 5.2.0
WARNING: Toolchain version is not supported: crosstool-ng-1.22.0-97-gc752ad5
Expected to see version: crosstool-ng-1.22.0-96-g2852398
Please check ESP-IDF setup instructions and update the toolchain, or proceed at your own risk.
Python requirements from /home/yhpark/st-device-sdk-c-ref/bsp/esp32_v3.3/requirements.txt are satisfied.`

`App "switch_example" version: v1.8.7-2-ga8226c6-dirty
CC /home/yhpark/st-device-sdk-c-ref/apps/esp32/switch_example/build/main/device_control.o
/home/yhpark/st-device-sdk-c-ref/apps/esp32/switch_example/main/device_control.c: In function 'get_button_event':
/home/yhpark/st-device-sdk-c-ref/apps/esp32/switch_example/main/device_control.c:52:20: error: format '%ld' expects argument of type 'long int', but argument 2 has type 'uint32_t {aka unsigned int}' [-Werror=format=]
             printf("Button event, val: %ld, tick: %lu\n", gpio_level, (uint32_t)xTaskGetTickCount());
                    ^
/home/yhpark/st-device-sdk-c-ref/apps/esp32/switch_example/main/device_control.c:52:20: error: format '%lu' expects argument of type 'long unsigned int', but argument 3 has type 'unsigned int' [-Werror=format=]
/home/yhpark/st-device-sdk-c-ref/apps/esp32/switch_example/main/device_control.c:52:20: error: format '%ld' expects argument of type 'long int', but argument 2 has type 'uint32_t {aka unsigned int}' [-Werror=format=]
/home/yhpark/st-device-sdk-c-ref/apps/esp32/switch_example/main/device_control.c:52:20: error: format '%lu' expects argument of type 'long unsigned int', but argument 3 has type 'unsigned int' [-Werror=format=]
cc1: some warnings being treated as errors
make[1]: *** [/home/yhpark/st-device-sdk-c-ref/bsp/esp32_v3.3/make/component_wrapper.mk:290: device_control.o] Error 1
make: *** [/home/yhpark/st-device-sdk-c-ref/bsp/esp32_v3.3/make/project.mk:552: component-main-build] Error 2`

Error that related with data format has occured…
how can i fix it?

**Comment by junyoun-kim** [comment]
Hello,

Could you try this example?(https://github.com/SmartThingsCommunity/st-device-sdk-c/tree/develop/example/esp32)

There is README file, so you can follow the instruction.

**Comment by asurada92** [comment]
> Hello,
> 
> Could you try this example?(https://github.com/SmartThingsCommunity/st-device-sdk-c/tree/develop/example/esp32)
> 
> There is README file, so you can follow the instruction.

Now I can use "idf.py build" and I can monitor the chip(esp32) state through idf.py flash
but how can I connect to smart things ?
Ofcoures, I already set the "device_info.json" and "onboarding_config.json"
and I already register my device on "smartthings.developer.samsung.com/"
But after I make qrcode
when I use the qrcode (in add device at smartthings app), the err is occured ("지원되지 않는 QR코드 이 QR코드로는 기기를 smartthings에 추가할 수 없습니다....)
Ofcoures I already activate developer mode (in iOS)

what's the problem? can you help me?

**Comment by junyoun-kim** [comment]
@asurada92 Could you let me know how you made qr code? and Could you share your qr code image?

**Comment by asurada92** [comment]
> @asurada92 Could you let me know how you made qr code? and Could you share your qr code image?

I made qr code referencing this page "https://github.com/SmartThingsCommunity/st-device-sdk-c/blob/develop/doc/getting_started.md"

Technically speaking, I use the python code below

==========================================
import qrcode

mnid = 'FFFF' # "FFFF" is an example. you should replace it with yours
onboardingId = '111' # "111" is an example. you should replace it with yours
serialNumber = 'STDKtest0001' # "STDKtest0001" is an example. you should replace it with yours
qrUrl = 'https://qr.samsungiots.com/?m=' + mnid + '&s=' + onboardingId + '&r=' + serialNumber
qrcode.QRCode(box_size=10, border=4)
img = qrcode.make(qrUrl)
img.save(serialNumber + '.png')
===========================================
here is the qr code image


![image](https://github.com/SmartThingsCommunity/st-device-sdk-c-ref/assets/28521753/b772defc-0e8d-4b22-a53e-6a1858a30ffb)

**Comment by junyoun-kim** [comment]
@asurada92 When I parsed the qrcode, it looks like below,

https://qr.samsungiots.com/?m=f3WE&s=onboarding&r=STDKrF6jsWAKcys9

And I think you put "onboarding" string instead of your onboardingId. Could you check this?

**Comment by asurada92** [comment]
> @asurada92 When I parsed the qrcode, it looks like below,
> 
> https://qr.samsungiots.com/?m=f3WE&s=onboarding&r=STDKrF6jsWAKcys9
> 
> And I think you put "onboarding" string instead of your onboardingId. Could you check this?

yes, you're right 
however,I already know that the onboarding string is on the qr-code
because the qr-generation code of mine is below

<img width="917" alt="image" src="https://github.com/SmartThingsCommunity/st-device-sdk-c-ref/assets/28521753/4d633a3a-b3d6-4f2b-b622-046945ca2b11">

I put the 'onboarding' string referencing "onboardingConfig.json" file like below
<img width="305" alt="image" src="https://github.com/SmartThingsCommunity/st-device-sdk-c-ref/assets/28521753/ce9aa480-86d3-4af0-918a-d6825ef63e06">

And I know that this onboardingconfig.json file can be downloaded from developer work space

I guess I can change onboarding ID through changing "onboarding display name"
<img width="847" alt="image" src="https://github.com/SmartThingsCommunity/st-device-sdk-c-ref/assets/28521753/86ae8d9a-c229-4532-b754-6f4cecaa661e">

isn't it? I guess this can be string

thank you for your co-operation

**Comment by junyoun-kim** [comment]
@asurada92 oh, Sorry for confusing you. you should put "setupId" in "onboardingId" value. So your case should be like below.

In python script,
....
onboardingId = '001'
....

We will change "onboardingId" to "setupId" in document to prevent confusion.

**Comment by asurada92** [comment]
> @asurada92 oh, Sorry for confusing you. you should put "setupId" in "onboardingId" value. So your case should be like below.
> 
> In python script, .... onboardingId = '001' ....
> 
> We will change "onboardingId" to "setupId" in document to prevent confusion.

Hello junyoun-kim,
I changed onboardingid to -> 001 but err still occured

here is device_info.json code, onboarding_config.json code
<img width="1738" alt="image" src="https://github.com/SmartThingsCommunity/st-device-sdk-c-ref/assets/28521753/2ecff49b-eb42-405c-98ed-db859b441272">

And this is qr-code that re-generated
![image](https://github.com/SmartThingsCommunity/st-device-sdk-c-ref/assets/28521753/3b81ad16-acdf-43f8-bb6c-f218955feaeb)

**Comment by junyoun-kim** [comment]
@asurada92 Is this same err? Could you let me know which err you are facing now?

**Comment by asurada92** [comment]
> @asurada92 Is this same err? Could you let me know which err you are facing now?

지원되지 않는 QR코드 이 QR코드로는 기기를 smartthings에 추가할 수 없습니다....)
Above err occured

**Comment by junyoun-kim** [comment]
@asurada92 Could you check your iOS ST app's samsung account is same as DevWS account? And also could you check enabling developer mode in ST app?

**Comment by asurada92** [comment]
<img width="400" alt="image" src="https://github.com/SmartThingsCommunity/st-device-sdk-c-ref/assets/28521753/9603aeef-e53e-4c26-b687-2c61f3bb2b6b">

![image](https://github.com/SmartThingsCommunity/st-device-sdk-c-ref/assets/28521753/9dee1ae7-cc79-4fde-8b49-15bf269760c5)

the two account is same


and 

![image](https://github.com/SmartThingsCommunity/st-device-sdk-c-ref/assets/28521753/bec903b4-fac5-4269-8a32-f364e8e716ab)


I also turned on the developer mode....

**Comment by junyoun-kim** [comment]
@asurada92 We found out there is problem in iOS ST APP for testing in developer mode. Sorry for letting you know this. We will let you know when fix is published.

Meanwhile you can try it with Android ST app.

**Comment by junyoun-kim** [comment]
@asurada92 iOS ST APP issue patch will be applied next app update.

**Comment by asurada92** [comment]
> @asurada92 iOS ST APP issue patch will be applied next app update.

When does the update will be on?

**Comment by junyoun-kim** [comment]
@asurada92 That will be Jan. 22.

**Comment by junyoun-kim** [comment]
Hello, @asurada92  Is there any more questions? We will close this issue if no more updates.
