### ISSUE TITLE
Request for source code error correction

### ISSUE THREAD

**Issue by KIMSUNIK** [SmartThingsCommunity/st-device-sdk-c-ref#140]
CAP_ENUM_MOTIONSENSOR_MOTION_VALUE_MAX
>> CAP_ENUM_TVOCHEALTHCONCERN_VALUE_MAX

https://github.com/SmartThingsCommunity/st-device-sdk-c-ref/blob/develop/apps/capability_sample/caps_tvocHealthConcern.c

line-30
static int caps_tvocHealthConcern_attr_tvocHealthConcern_str2idx(const char *value)
{
    int index;

    for (index = 0; index < CAP_ENUM_MOTIONSENSOR_MOTION_VALUE_MAX; index++) {
        if (!strcmp(value, caps_helper_tvocHealthConcern.attr_tvocHealthConcern.values[index])) {
            return index;
        }
    }
    return -1;
}

**Comment by junyoun-kim** [comment]
Thanks, we fix it with this #141
