### ISSUE TITLE
How to enable developer mode in iPhone?

### ISSUE THREAD

**Issue by taehyun9203** [SmartThingsCommunity/st-device-sdk-c-ref#152]
I am writing to inquire about enabling the developer mode in the SmartThings app. 

Currently, I am using an iPhone 12 Pro running iOS 17. 

I attempted to press the "About SmartThings" button for five seconds but was unable to locate the developer mode.

Could you please provide guidance on how to enable the developer mode on my iPhone?

**Comment by jonggab-park** [comment]
Could you share your ST app version?
There are no problems with our test.
When “About SmartThings” is long-pressed for more than 7 seconds, the developer mode button is showed.

**Comment by taehyun9203** [comment]
my st version is 1.7.14.22
I pressed the button during 10 seconds, but the mode was not shown.

**Comment by jonggab-park** [comment]
We are also using the same version, but it is working well.
If the problem is persisted, register the question by Cotact us - Ask question.
If the question is reported to us, we could check the mobile log.

**Comment by taehyun9203** [comment]
I will register the question.

I found an question which cannot enable developer mode in iPhone.

https://community.smartthings.com/t/smartthings-developer-mode-not-working/259629/33

They suggested to use Android Phone instead of using iPhone till fixing problem.

Did you read the question?

**Comment by jonggab-park** [comment]
This issue may not be reported to us because to be enable developer mode isn't a SDK specific feature.
It seemed like it had been reported to ST app engineer.
This problem seems to only occur for people who are using developer mode on iOS for the first time.
I will check the fixed ST version on iOS, but it seems to use Android phone before the fixed version is released.
Thank you for the report.

**Comment by taehyun9203** [comment]
I understand that this is a problem of ST app engineer.
Maybe I will wait for new version of ST..
Thank you for replying my question.
