### ISSUE TITLE
Broken URL for codelabs in getting_started.md

### ISSUE THREAD

**Issue by karanpanjabi** [SmartThingsCommunity/st-device-sdk-c-ref#21]
The first para of Workflow section in getting_started.md mentions the following: "You can also refer to the [Code Lab data of the 2019 Samsung Developer Conference](https://developer.samsung.com/codelab/smartThings/device/overview). It will be more practical for you to understand the STDK."

The URL: https://developer.samsung.com/codelab/smartThings/device/overview gives a 404 response.

**Comment by Kwang-Hui** [comment]
Hi, Sorry for your inconvenience.
URL has fixed at `develop` branch. not yet merged to `master` branch.
https://github.com/SmartThingsCommunity/st-device-sdk-c-ref/blob/develop/doc/getting_started.md

Here is direct link for that contents: https://developer.samsung.com/codelab/smartthings/smartthings-device-sdk/overview.html
