### ISSUE TITLE
Kconfig not working for ESP8266

### ISSUE THREAD

**Issue by momo1** [SmartThingsCommunity/st-device-sdk-c-ref#64]
Hi,

The Smartthings Kconfig file is not being picked up when using ESP8266 (works fine for ESP32). I copied the Kconfig from `iot-core/src` to my project's main/ so that menuconfig would pick it up. It's either that or define all the config variables manually, including "STDK_IOT_CORE" without which the source code won't even compile.

**Comment by Kwang-Hui** [comment]
Hi,
Could you try like below?

```sh
$ python build.py apps/esp8266/switch_example/ menuconfig
```
`Component config` --> `SmartThings IoT Core`

![image](https://user-images.githubusercontent.com/54692798/96556055-7e490680-12f3-11eb-8e0c-6a7523f0b6ab.png)
![image](https://user-images.githubusercontent.com/54692798/96556114-8c972280-12f3-11eb-98ef-a09f5c10e7ac.png)

**Comment by Kwang-Hui** [comment]
This issue is closing now.
Please re-open if you still have this problem.

Thanks.
