### ISSUE TITLE
IoT Ethernet device onboarding support

### ISSUE THREAD

**Issue by f34rdotcom** [SmartThingsCommunity/st-device-sdk-c-ref#69]
How can I adopt using Ethernet and not WiFi?

I want be be able to Adopt using an ESP32 with Ethernet in my project in cases where Wifi is not suitable. I have several boards to work with to test but not sure where to start. It is not clear to me how the ST App will adopt an Ethernet based IoT device. Is it using UPNP/SSDP for discovery or does the user have to know the IP address?

https://www.olimex.com/Products/IoT/ESP32/ESP32-EVB/open-source-hardware
https://www.olimex.com/Products/IoT/ESP32/ESP32-POE-ISO/open-source-hardware

**Comment by Kwang-Hui** [comment]
Hi, unfortunately we don't have plan for ethernet support for now.
If you have further queries, please open new issue. thank you.
