### ISSUE TITLE
st_dev.h cannot be found

### ISSUE THREAD

**Issue by alienatorZ** [SmartThingsCommunity/st-device-sdk-c-ref#84]
When I create a new project on the ESP 8266 and after following the instructions on https://smartthings.developer.samsung.com/docs/devices/direct-connected-devices/device-app.html I get the error: fatal error: st_dev.h: No such file or directory. 

My Makefile looks like: PROJECT_NAME := hello-world
EXTRA_COMPONENT_DIRS := ${IDF_PATH}/../../iot-core
include $(IDF_PATH)/make/project.mk

What do I need to change to find the header file?

Thanks!

**Comment by alienatorZ** [comment]
This was due to not enabling Smarthings core in menu config under "Component Config."

**Comment by PannagSDesai** [comment]
Man you saved me, seriously Thanks a lot
